### PR TITLE
Feature/footer

### PR DESCRIPTION
**Pull request by Majid-pkz**
add footer component.

### CODE REVIEW

**Comment by Majid-pkz** [comment]
I will change twitter icon to X.
I will also improve footer.module.css  specially the class naming. 

please let me know what else could be improved.

**Review by bhumkarpratik — COMMENTED** [review]
This is some real solid work.
It would be great if everything would be a hyperlink instead of text. 
We could add accessibility to it as a hyperlink and have the mouse icon to be accordingly.

Here are the links to our socials:
https://www.facebook.com/neurodiversityacademy
https://www.instagram.com/neurodiversityacademy/
https://www.linkedin.com/company/neurodiversity-academy/
https://twitter.com/neuro_d_academy

**Comment by bhumkarpratik** [comment]
> I was not sure about these two attributes for a tag:
> 
> 1. **aria-label**='Facebook'
> 2. **title**='Visit our Facebook page'.
>    But I tried to follow the MDN suggestion: "Links that open in a new tab/window via target="_blank", or links that point to a download file should indicate what will happen when the link is followed"

What you've done looks great!

**Review by bhumkarpratik — APPROVED** [review]
Looks awesome!

**Pull request merged**
